### PR TITLE
Fix link to template (always latest release)

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by krono** [comment]
is there a way to directly go to the zip?

**Comment by fniephaus** [comment]
I don't think there is (see [here](https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release)). You could, however, let the link point to the [`master` zip](https://github.com/programming-journal/programming/archive/master.zip) or any other branch.

**Comment by krono** [comment]
Ok, this won't work, as we're not linking to the branch snapshot but an uploaded template zip

**Comment by fniephaus** [comment]
The link is still broken on the website :(

**Pull request closed without merging**
