### PR TITLE
Artifact evaluation badges 2.0

### PR DESCRIPTION
**Pull request by codeZeilen**
This is a first draft of changes to the artifact evaluation pages reflecting the new badges.

### CODE REVIEW

**Comment by krono** [comment]
oh, do I need to make new badges?

**Comment by codeZeilen** [comment]
At one point yes, but not yet. :) The wording is not final yet. Also: The design can stay the way it is. We only change labels and probably want to add a v2 (or something like that) at the bottom.

**Comment by krono** [comment]
I'm not fond of versioned badges, but I recon the approach is practical and usefull.

**Comment by krono** [comment]
🚀

**Pull request merged**
